name: Test
on:
  workflow_dispatch: # manually triggered
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # schedule:
  #   - cron: '45 9 * * *' # daily at 9:45 UTC (11:45 EEST)

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Unit test
        run: npm test
